[metadata]
  name = "blocksync-historical"
  author = "derrandz"

[global]
  plan = "celestia"
  case = "blocksync-historical"
  total_instances = 36
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false

# we define 1 validator that produces 500kb blocks
# which results in eds of size 64
[global.run.test_params]
  execution-time = "20"
  persistent-peers = "1"
  submit-times = "10"
  msg-size = "500000"
  validator = "1"
  bridge = "3"
  full = "16"
  historical = "16"
  block-height = "30"
  otel-collector-address = "" # insert your otel collector address here
  getter = "ipld"
  peers-limit = "3"
  bootstrapper = "true"
  interconnect-bridges = "true"
  multibootstrap = "false"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = "8Gi"
    cpu = "4"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "validator"

[[groups]]
  id = "bridges"
  builder = "docker:generic"
  [groups.resources]
    memory = "8Gi"
    cpu = "4"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "bridge"

[[groups]]
  id = "fulls"
  builder = "docker:generic"
  [groups.resources]
    memory = "8Gi"
    cpu = "4"
  [groups.instances]
    count = 16
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "full"

[[groups]]
  id = "historicals"
  builder = "docker:generic"
  [groups.resources]
    memory = "8Gi"
    cpu = "4"
  [groups.instances]
    count = 16
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "historical"
