[metadata]
  name = "qgb-test"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "qgb-test"
  total_instances = 21
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false

[global.run.test_params]
  execution-time = "15"
  latency = "0"
  bandwidth = "320Mib"
  orchestrator = "20"
  validator = "20"
  seed = "1"
  persistent-peers = "2"
  msg-size = "100000"

[[groups]]
  id = "orchestrators"
  builder = "docker:generic"
  [groups.resources]
  memory = "4Gi"
  cpu = "3500m"
  [groups.instances]
    count = 20
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""

[[groups]]
  id = "seeds"
  builder = "docker:generic"
  [groups.resources]
  memory = "2Gi"
  cpu = "2"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""