[metadata]
  name = "qgb-test"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "qgb-test"
  total_instances = 4
  builder = "docker:generic"
  runner = "local:docker"
  disable_metrics = false

[global.run.test_params]
  execution-time = "10"
  latency = "0"
  bandwidth = "320Mib"
  orchestrator = "4"
  msg-size = "100000"

[[groups]]
  id = "orchestrators"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 4
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
